version: '3.9'

services:
  app:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/js:/backend/js
    environment:
      - CHOKIDAR_USEPOLLING=true  # Ensures React detects file changes
    command: npm run dev  # Use a dev script that supports live reload
    restart: unless-stopped
    networks:
      - default
    ports:
      - "3000:3000"


  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app  # Sync local project with container for hot reloading
      - /app/node_modules  # Prevents overwriting installed dependencies
    depends_on:
      - app
    ports:
      - "5000:5000"
    networks:
      - default
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enables live reload inside Docker


  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # Use a separate config for dev mode
    networks:
      - default
    restart: unless-stopped

networks:
  default:
    driver: bridge